### ISSUE TITLE
advanced selection keeping

### ISSUE THREAD

**Issue by FlorianWendelborn** [severinkaderli/atom-reverser#7]
I think it would be more reasonable, when the selection would only be kept **for user-selected text**, not for script-selected text. This would probably only require ~3 lines of code.

If you think that should be implemented, either do it, or tell me you would merge that. I will then submit a pull request as soon as I can.

**Comment by severinkaderli** [comment]
I would merge such an addition, but I myself don't have the time to work on this project at the moment.
